//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap dw_icon {
            get {
                object obj = ResourceManager.GetObject("dw_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0:1:1&quot;;&quot;HaShaShiN&quot;;&quot;Lugar Oscuro&quot;;&quot;[CherubiM]&quot;;&quot;Sky-Marshal&quot;;&quot;0&quot;;
        ///&quot;0:12:1&quot;;&quot;The_Odo666&quot;;&quot;Terra&quot;;&quot;[Asgard]&quot;;&quot;Lieutenant&quot;;&quot;0&quot;;
        ///&quot;0:2:2&quot;;&quot;Kane&quot;;&quot;Der Verfluchte&quot;;&quot;[CherubiM]&quot;;&quot;Sky-Marshal&quot;;&quot;0&quot;;
        ///&quot;0:5:4&quot;;&quot;Shinchan&quot;;&quot;Alfa 4&quot;;&quot;Nocturnal&quot;;&quot;Sky-Marshal&quot;;&quot;0&quot;;
        ///&quot;0:4:5&quot;;&quot;Alpharius&quot;;&quot;Outworld&quot;;&quot;Nocturnal&quot;;&quot;Major&quot;;&quot;0&quot;;
        ///&quot;0:25:5&quot;;&quot;vito2308&quot;;&quot;Helms Klamm&quot;;&quot;Nocturnal&quot;;&quot;Sky-Marshal&quot;;&quot;0&quot;;
        ///&quot;0:8:6&quot;;&quot;Ivanhoe&quot;;&quot;Wolfenstein&quot;;&quot;-&quot;;&quot;Captain&quot;;&quot;0&quot;;
        ///&quot;0:23:7&quot;;&quot;Son-Goku&quot;;&quot;dbz&quot;;&quot;sommer-senza&quot;;&quot;Sergeant&quot;;&quot;0&quot;;
        ///&quot;0:24:7&quot;;&quot;CrunK&quot;;&quot;Remix&quot;;&quot;-&quot;;&quot;Corp [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string karten {
            get {
                return ResourceManager.GetString("karten", resourceCulture);
            }
        }
    }
}
